PGPASSWORD=password psql -U $PG_USER -h $PG_HOST -d $PG_DATABASE -v "ON_ERROR_STOP=1" --set=sslmode=require -c 'CREATE EXTENSION IF NOT EXISTS "pgcrypto"'
PGPASSWORD=password psql -U $PG_USER -h $PG_HOST -d $PG_DATABASE -v "ON_ERROR_STOP=1" --set=sslmode=require -f ./db/001-setup.sql
PGPASSWORD=password psql -U $PG_USER -h $PG_HOST -d $PG_DATABASE -v "ON_ERROR_STOP=1" --set=sslmode=require -f ./db/002-hypertable.sql
PGPASSWORD=password psql -U $PG_USER -h $PG_HOST -d $PG_DATABASE -v "ON_ERROR_STOP=1" --set=sslmode=require -f ./db/003-locations_add_columns_set_defaults.sql
PGPASSWORD=password psql -U $PG_USER -h $PG_HOST -d $PG_DATABASE -v "ON_ERROR_STOP=1" --set=sslmode=require -f ./db/004-fallbackphone.sql
PGPASSWORD=password psql -U $PG_USER -h $PG_HOST -d $PG_DATABASE -v "ON_ERROR_STOP=1" --set=sslmode=require -f ./db/005-human_read_location.sql
PGPASSWORD=password psql -U $PG_USER -h $PG_HOST -d $PG_DATABASE -v "ON_ERROR_STOP=1" --set=sslmode=require -f ./db/006-sessions-alertReason.sql
PGPASSWORD=password psql -U $PG_USER -h $PG_HOST -d $PG_DATABASE -v "ON_ERROR_STOP=1" --set=sslmode=require -f ./db/007-rename_location_human.sql
PGPASSWORD=password psql -U $PG_USER -h $PG_HOST -d $PG_DATABASE -v "ON_ERROR_STOP=1" --set=sslmode=require -f ./db/008-drop_unused_tables.sql
PGPASSWORD=password psql -U $PG_USER -h $PG_HOST -d $PG_DATABASE -v "ON_ERROR_STOP=1" --set=sslmode=require -f ./db/009-add-particlecoreid-to-locations.sql
PGPASSWORD=password psql -U $PG_USER -h $PG_HOST -d $PG_DATABASE -v "ON_ERROR_STOP=1" --set=sslmode=require -f ./db/010-rename-waiting-for-response.sql
PGPASSWORD=password psql -U $PG_USER -h $PG_HOST -d $PG_DATABASE -v "ON_ERROR_STOP=1" --set=sslmode=require -f ./db/011-add-radar-type-to-locations.sql
PGPASSWORD=password psql -U $PG_USER -h $PG_HOST -d $PG_DATABASE -v "ON_ERROR_STOP=1" --set=sslmode=require -f ./db/012-rename-heartbeat-alert-columns.sql
PGPASSWORD=password psql -U $PG_USER -h $PG_HOST -d $PG_DATABASE -v "ON_ERROR_STOP=1" --set=sslmode=require -f ./db/013-update-locations-table-for-forms.sql
PGPASSWORD=password psql -U $PG_USER -h $PG_HOST -d $PG_DATABASE -v "ON_ERROR_STOP=1" --set=sslmode=require -f ./db/014-alterfallbackphonenumbertobeanarray.sql
PGPASSWORD=password psql -U $PG_USER -h $PG_HOST -d $PG_DATABASE -v "ON_ERROR_STOP=1" --set=sslmode=require -f ./db/015-add-api-key-to-locations.sql
PGPASSWORD=password psql -U $PG_USER -h $PG_HOST -d $PG_DATABASE -v "ON_ERROR_STOP=1" --set=sslmode=require -f ./db/016-alterheatbeackphonenumbertobeanarray.sql
PGPASSWORD=password psql -U $PG_USER -h $PG_HOST -d $PG_DATABASE -v "ON_ERROR_STOP=1" --set=sslmode=require -f ./db/017-add-is-active-to-locations.sql
PGPASSWORD=password psql -U $PG_USER -h $PG_HOST -d $PG_DATABASE -v "ON_ERROR_STOP=1" --set=sslmode=require -f ./db/018-refactor-sessions.sql
PGPASSWORD=password psql -U $PG_USER -h $PG_HOST -d $PG_DATABASE -v "ON_ERROR_STOP=1" --set=sslmode=require -f ./db/019-change-alert-reason-values.sql
PGPASSWORD=password psql -U $PG_USER -h $PG_HOST -d $PG_DATABASE -v "ON_ERROR_STOP=1" --set=sslmode=require -f ./db/020-add-responded-at-to-sessions.sql
PGPASSWORD=password psql -U $PG_USER -h $PG_HOST -d $PG_DATABASE -v "ON_ERROR_STOP=1" --set=sslmode=require -f ./db/021-add-client-from-phone-number.sql
PGPASSWORD=password psql -U $PG_USER -h $PG_HOST -d $PG_DATABASE -v "ON_ERROR_STOP=1" --set=sslmode=require -f ./db/022-add-siren-particle-id.sql
PGPASSWORD=password psql -U $PG_USER -h $PG_HOST -d $PG_DATABASE -v "ON_ERROR_STOP=1" --set=sslmode=require -f ./db/023-add-responder-push-id.sql
PGPASSWORD=password psql -U $PG_USER -h $PG_HOST -d $PG_DATABASE -v "ON_ERROR_STOP=1" --set=sslmode=require -f ./db/024-add-sent-low-battery-alert-at-to-locations.sql
PGPASSWORD=password psql -U $PG_USER -h $PG_HOST -d $PG_DATABASE -v "ON_ERROR_STOP=1" --set=sslmode=require -f ./db/025-add-notifications.sql
PGPASSWORD=password psql -U $PG_USER -h $PG_HOST -d $PG_DATABASE -v "ON_ERROR_STOP=1" --set=sslmode=require -f ./db/026-add-sent-vitals-alert-at.sql
PGPASSWORD=password psql -U $PG_USER -h $PG_HOST -d $PG_DATABASE -v "ON_ERROR_STOP=1" --set=sslmode=require -f ./db/027-add-location-created-and-updated-dates.sql
PGPASSWORD=password psql -U $PG_USER -h $PG_HOST -d $PG_DATABASE -v "ON_ERROR_STOP=1" --set=sslmode=require -f ./db/028-refactor-clients.sql
PGPASSWORD=password psql -U $PG_USER -h $PG_HOST -d $PG_DATABASE -v "ON_ERROR_STOP=1" --set=sslmode=require -f ./db/029-drop-location-radartype.sql
PGPASSWORD=password psql -U $PG_USER -h $PG_HOST -d $PG_DATABASE -v "ON_ERROR_STOP=1" --set=sslmode=require -f ./db/030-add-sensor-vitals.sql
PGPASSWORD=password psql -U $PG_USER -h $PG_HOST -d $PG_DATABASE -v "ON_ERROR_STOP=1" --set=sslmode=require -f ./db/031-add-session-and-sensors-vitals-indices.sql
PGPASSWORD=password psql -U $PG_USER -h $PG_HOST -d $PG_DATABASE -v "ON_ERROR_STOP=1" --set=sslmode=require -f ./db/032-add-sensor-vitals-cache.sql
PGPASSWORD=password psql -U $PG_USER -h $PG_HOST -d $PG_DATABASE -v "ON_ERROR_STOP=1" --set=sslmode=require -f ./db/033-remove-siren.sql
PGPASSWORD=password psql -U $PG_USER -h $PG_HOST -d $PG_DATABASE -v "ON_ERROR_STOP=1" --set=sslmode=require -f ./db/034-alter-session-schema.sql
PGPASSWORD=password psql -U $PG_USER -h $PG_HOST -d $PG_DATABASE -v "ON_ERROR_STOP=1" --set=sslmode=require -f ./db/035-add-session-responded-by-phone-number.sql
PGPASSWORD=password psql -U $PG_USER -h $PG_HOST -d $PG_DATABASE -v "ON_ERROR_STOP=1" --set=sslmode=require -f ./db/036-alterresponderphonenumberstobeanarray.sql
PGPASSWORD=password psql -U $PG_USER -h $PG_HOST -d $PG_DATABASE -v "ON_ERROR_STOP=1" --set=sslmode=require -f ./db/037-add-client-language.sql
PGPASSWORD=password psql -U $PG_USER -h $PG_HOST -d $PG_DATABASE -v "ON_ERROR_STOP=1" --set=sslmode=require -f ./db/038-add-client-extension-table.sql
PGPASSWORD=password psql -U $PG_USER -h $PG_HOST -d $PG_DATABASE -v "ON_ERROR_STOP=1" --set=sslmode=require -f ./db/039-remove-fsm-and-door-core-id.sql